name: Update README Last Updated
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *' # Roda todo dia às 8h UTC (5h da manhã no Brasil)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Update README
        run: |
          sed -i "s||$(date -u +"%d de %B de %Y, %H:%M:%S UTC")|" README.md
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -am "Docs: auto-update last updated" || exit 0
          git push
